/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BotsForexRouteImport } from './routes/bots.forex'
import { Route as BotsIndicesRouteImport } from './routes/bots.indices'
import { Route as OauthCallbackRouteImport } from './routes/oauth/callback'
import { Route as BotsForexIndexRouteImport } from './routes/bots.forex.index'
import { Route as BotsIndicesIndexRouteImport } from './routes/bots.indices.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsForexRoute = BotsForexRouteImport.update({
  id: '/bots/forex',
  path: '/bots/forex',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsIndicesRoute = BotsIndicesRouteImport.update({
  id: '/bots/indices',
  path: '/bots/indices',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsForexIndexRoute = BotsForexIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BotsForexRoute,
} as any)
const BotsIndicesIndexRoute = BotsIndicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BotsIndicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/bots/forex': typeof BotsForexRouteWithChildren
  '/bots/indices': typeof BotsIndicesRouteWithChildren
  '/oauth/callback': typeof OauthCallbackRoute
  '/bots/forex/': typeof BotsForexIndexRoute
  '/bots/indices/': typeof BotsIndicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/bots/forex': typeof BotsForexIndexRoute
  '/bots/indices': typeof BotsIndicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/bots/forex': typeof BotsForexRouteWithChildren
  '/bots/indices': typeof BotsIndicesRouteWithChildren
  '/oauth/callback': typeof OauthCallbackRoute
  '/bots/forex/': typeof BotsForexIndexRoute
  '/bots/indices/': typeof BotsIndicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/bots/forex'
    | '/bots/indices'
    | '/oauth/callback'
    | '/bots/forex/'
    | '/bots/indices/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/oauth/callback' | '/bots/forex' | '/bots/indices'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/bots/forex'
    | '/bots/indices'
    | '/oauth/callback'
    | '/bots/forex/'
    | '/bots/indices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  BotsForexRoute: typeof BotsForexRouteWithChildren
  BotsIndicesRoute: typeof BotsIndicesRouteWithChildren
  OauthCallbackRoute: typeof OauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots/forex': {
      id: '/bots/forex'
      path: '/bots/forex'
      fullPath: '/bots/forex'
      preLoaderRoute: typeof BotsForexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots/indices': {
      id: '/bots/indices'
      path: '/bots/indices'
      fullPath: '/bots/indices'
      preLoaderRoute: typeof BotsIndicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots/forex/': {
      id: '/bots/forex/'
      path: '/'
      fullPath: '/bots/forex/'
      preLoaderRoute: typeof BotsForexIndexRouteImport
      parentRoute: typeof BotsForexRoute
    }
    '/bots/indices/': {
      id: '/bots/indices/'
      path: '/'
      fullPath: '/bots/indices/'
      preLoaderRoute: typeof BotsIndicesIndexRouteImport
      parentRoute: typeof BotsIndicesRoute
    }
  }
}

interface BotsForexRouteChildren {
  BotsForexIndexRoute: typeof BotsForexIndexRoute
}

const BotsForexRouteChildren: BotsForexRouteChildren = {
  BotsForexIndexRoute: BotsForexIndexRoute,
}

const BotsForexRouteWithChildren = BotsForexRoute._addFileChildren(
  BotsForexRouteChildren,
)

interface BotsIndicesRouteChildren {
  BotsIndicesIndexRoute: typeof BotsIndicesIndexRoute
}

const BotsIndicesRouteChildren: BotsIndicesRouteChildren = {
  BotsIndicesIndexRoute: BotsIndicesIndexRoute,
}

const BotsIndicesRouteWithChildren = BotsIndicesRoute._addFileChildren(
  BotsIndicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  BotsForexRoute: BotsForexRouteWithChildren,
  BotsIndicesRoute: BotsIndicesRouteWithChildren,
  OauthCallbackRoute: OauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
