/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BotsForexRouteImport } from './routes/bots.forex'
import { Route as BotsIndicesRouteImport } from './routes/bots.indices'
import { Route as OauthCallbackRouteImport } from './routes/oauth/callback'
import { Route as BotsForexIndexRouteImport } from './routes/bots.forex.index'
import { Route as BotsForexAnalysisRouteImport } from './routes/bots.forex.analysis'
import { Route as BotsForexHistoryRouteImport } from './routes/bots.forex.history'
import { Route as BotsForexMarketsRouteImport } from './routes/bots.forex.markets'
import { Route as BotsForexSettingsRouteImport } from './routes/bots.forex.settings'
import { Route as BotsForexTradeRouteImport } from './routes/bots.forex.trade'
import { Route as BotsIndicesIndexRouteImport } from './routes/bots.indices.index'
import { Route as BotsIndicesAnalysisRouteImport } from './routes/bots.indices.analysis'
import { Route as BotsIndicesHistoryRouteImport } from './routes/bots.indices.history'
import { Route as BotsIndicesMarketsRouteImport } from './routes/bots.indices.markets'
import { Route as BotsIndicesSettingsRouteImport } from './routes/bots.indices.settings'
import { Route as BotsIndicesTradeRouteImport } from './routes/bots.indices.trade'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsForexRoute = BotsForexRouteImport.update({
  id: '/bots/forex',
  path: '/bots/forex',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsIndicesRoute = BotsIndicesRouteImport.update({
  id: '/bots/indices',
  path: '/bots/indices',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsForexIndexRoute = BotsForexIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BotsForexRoute,
} as any)
const BotsForexAnalysisRoute = BotsForexAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => BotsForexRoute,
} as any)
const BotsForexHistoryRoute = BotsForexHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => BotsForexRoute,
} as any)
const BotsForexMarketsRoute = BotsForexMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => BotsForexRoute,
} as any)
const BotsForexSettingsRoute = BotsForexSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BotsForexRoute,
} as any)
const BotsForexTradeRoute = BotsForexTradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => BotsForexRoute,
} as any)
const BotsIndicesIndexRoute = BotsIndicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BotsIndicesRoute,
} as any)
const BotsIndicesAnalysisRoute = BotsIndicesAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => BotsIndicesRoute,
} as any)
const BotsIndicesHistoryRoute = BotsIndicesHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => BotsIndicesRoute,
} as any)
const BotsIndicesMarketsRoute = BotsIndicesMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => BotsIndicesRoute,
} as any)
const BotsIndicesSettingsRoute = BotsIndicesSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BotsIndicesRoute,
} as any)
const BotsIndicesTradeRoute = BotsIndicesTradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => BotsIndicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/bots/forex': typeof BotsForexRouteWithChildren
  '/bots/indices': typeof BotsIndicesRouteWithChildren
  '/oauth/callback': typeof OauthCallbackRoute
  '/bots/forex/analysis': typeof BotsForexAnalysisRoute
  '/bots/forex/history': typeof BotsForexHistoryRoute
  '/bots/forex/markets': typeof BotsForexMarketsRoute
  '/bots/forex/settings': typeof BotsForexSettingsRoute
  '/bots/forex/trade': typeof BotsForexTradeRoute
  '/bots/indices/analysis': typeof BotsIndicesAnalysisRoute
  '/bots/indices/history': typeof BotsIndicesHistoryRoute
  '/bots/indices/markets': typeof BotsIndicesMarketsRoute
  '/bots/indices/settings': typeof BotsIndicesSettingsRoute
  '/bots/indices/trade': typeof BotsIndicesTradeRoute
  '/bots/forex/': typeof BotsForexIndexRoute
  '/bots/indices/': typeof BotsIndicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/bots/forex/analysis': typeof BotsForexAnalysisRoute
  '/bots/forex/history': typeof BotsForexHistoryRoute
  '/bots/forex/markets': typeof BotsForexMarketsRoute
  '/bots/forex/settings': typeof BotsForexSettingsRoute
  '/bots/forex/trade': typeof BotsForexTradeRoute
  '/bots/indices/analysis': typeof BotsIndicesAnalysisRoute
  '/bots/indices/history': typeof BotsIndicesHistoryRoute
  '/bots/indices/markets': typeof BotsIndicesMarketsRoute
  '/bots/indices/settings': typeof BotsIndicesSettingsRoute
  '/bots/indices/trade': typeof BotsIndicesTradeRoute
  '/bots/forex': typeof BotsForexIndexRoute
  '/bots/indices': typeof BotsIndicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/bots/forex': typeof BotsForexRouteWithChildren
  '/bots/indices': typeof BotsIndicesRouteWithChildren
  '/oauth/callback': typeof OauthCallbackRoute
  '/bots/forex/analysis': typeof BotsForexAnalysisRoute
  '/bots/forex/history': typeof BotsForexHistoryRoute
  '/bots/forex/markets': typeof BotsForexMarketsRoute
  '/bots/forex/settings': typeof BotsForexSettingsRoute
  '/bots/forex/trade': typeof BotsForexTradeRoute
  '/bots/indices/analysis': typeof BotsIndicesAnalysisRoute
  '/bots/indices/history': typeof BotsIndicesHistoryRoute
  '/bots/indices/markets': typeof BotsIndicesMarketsRoute
  '/bots/indices/settings': typeof BotsIndicesSettingsRoute
  '/bots/indices/trade': typeof BotsIndicesTradeRoute
  '/bots/forex/': typeof BotsForexIndexRoute
  '/bots/indices/': typeof BotsIndicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/bots/forex'
    | '/bots/indices'
    | '/oauth/callback'
    | '/bots/forex/analysis'
    | '/bots/forex/history'
    | '/bots/forex/markets'
    | '/bots/forex/settings'
    | '/bots/forex/trade'
    | '/bots/indices/analysis'
    | '/bots/indices/history'
    | '/bots/indices/markets'
    | '/bots/indices/settings'
    | '/bots/indices/trade'
    | '/bots/forex/'
    | '/bots/indices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/oauth/callback'
    | '/bots/forex/analysis'
    | '/bots/forex/history'
    | '/bots/forex/markets'
    | '/bots/forex/settings'
    | '/bots/forex/trade'
    | '/bots/indices/analysis'
    | '/bots/indices/history'
    | '/bots/indices/markets'
    | '/bots/indices/settings'
    | '/bots/indices/trade'
    | '/bots/forex'
    | '/bots/indices'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/bots/forex'
    | '/bots/indices'
    | '/oauth/callback'
    | '/bots/forex/analysis'
    | '/bots/forex/history'
    | '/bots/forex/markets'
    | '/bots/forex/settings'
    | '/bots/forex/trade'
    | '/bots/indices/analysis'
    | '/bots/indices/history'
    | '/bots/indices/markets'
    | '/bots/indices/settings'
    | '/bots/indices/trade'
    | '/bots/forex/'
    | '/bots/indices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  BotsForexRoute: typeof BotsForexRouteWithChildren
  BotsIndicesRoute: typeof BotsIndicesRouteWithChildren
  OauthCallbackRoute: typeof OauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots/forex': {
      id: '/bots/forex'
      path: '/bots/forex'
      fullPath: '/bots/forex'
      preLoaderRoute: typeof BotsForexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots/indices': {
      id: '/bots/indices'
      path: '/bots/indices'
      fullPath: '/bots/indices'
      preLoaderRoute: typeof BotsIndicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots/forex/': {
      id: '/bots/forex/'
      path: '/'
      fullPath: '/bots/forex/'
      preLoaderRoute: typeof BotsForexIndexRouteImport
      parentRoute: typeof BotsForexRoute
    }
    '/bots/forex/analysis': {
      id: '/bots/forex/analysis'
      path: '/analysis'
      fullPath: '/bots/forex/analysis'
      preLoaderRoute: typeof BotsForexAnalysisRouteImport
      parentRoute: typeof BotsForexRoute
    }
    '/bots/forex/history': {
      id: '/bots/forex/history'
      path: '/history'
      fullPath: '/bots/forex/history'
      preLoaderRoute: typeof BotsForexHistoryRouteImport
      parentRoute: typeof BotsForexRoute
    }
    '/bots/forex/markets': {
      id: '/bots/forex/markets'
      path: '/markets'
      fullPath: '/bots/forex/markets'
      preLoaderRoute: typeof BotsForexMarketsRouteImport
      parentRoute: typeof BotsForexRoute
    }
    '/bots/forex/settings': {
      id: '/bots/forex/settings'
      path: '/settings'
      fullPath: '/bots/forex/settings'
      preLoaderRoute: typeof BotsForexSettingsRouteImport
      parentRoute: typeof BotsForexRoute
    }
    '/bots/forex/trade': {
      id: '/bots/forex/trade'
      path: '/trade'
      fullPath: '/bots/forex/trade'
      preLoaderRoute: typeof BotsForexTradeRouteImport
      parentRoute: typeof BotsForexRoute
    }
    '/bots/indices/': {
      id: '/bots/indices/'
      path: '/'
      fullPath: '/bots/indices/'
      preLoaderRoute: typeof BotsIndicesIndexRouteImport
      parentRoute: typeof BotsIndicesRoute
    }
    '/bots/indices/analysis': {
      id: '/bots/indices/analysis'
      path: '/analysis'
      fullPath: '/bots/indices/analysis'
      preLoaderRoute: typeof BotsIndicesAnalysisRouteImport
      parentRoute: typeof BotsIndicesRoute
    }
    '/bots/indices/history': {
      id: '/bots/indices/history'
      path: '/history'
      fullPath: '/bots/indices/history'
      preLoaderRoute: typeof BotsIndicesHistoryRouteImport
      parentRoute: typeof BotsIndicesRoute
    }
    '/bots/indices/markets': {
      id: '/bots/indices/markets'
      path: '/markets'
      fullPath: '/bots/indices/markets'
      preLoaderRoute: typeof BotsIndicesMarketsRouteImport
      parentRoute: typeof BotsIndicesRoute
    }
    '/bots/indices/settings': {
      id: '/bots/indices/settings'
      path: '/settings'
      fullPath: '/bots/indices/settings'
      preLoaderRoute: typeof BotsIndicesSettingsRouteImport
      parentRoute: typeof BotsIndicesRoute
    }
    '/bots/indices/trade': {
      id: '/bots/indices/trade'
      path: '/trade'
      fullPath: '/bots/indices/trade'
      preLoaderRoute: typeof BotsIndicesTradeRouteImport
      parentRoute: typeof BotsIndicesRoute
    }
  }
}

interface BotsForexRouteChildren {
  BotsForexAnalysisRoute: typeof BotsForexAnalysisRoute
  BotsForexHistoryRoute: typeof BotsForexHistoryRoute
  BotsForexMarketsRoute: typeof BotsForexMarketsRoute
  BotsForexSettingsRoute: typeof BotsForexSettingsRoute
  BotsForexTradeRoute: typeof BotsForexTradeRoute
  BotsForexIndexRoute: typeof BotsForexIndexRoute
}

const BotsForexRouteChildren: BotsForexRouteChildren = {
  BotsForexAnalysisRoute: BotsForexAnalysisRoute,
  BotsForexHistoryRoute: BotsForexHistoryRoute,
  BotsForexMarketsRoute: BotsForexMarketsRoute,
  BotsForexSettingsRoute: BotsForexSettingsRoute,
  BotsForexTradeRoute: BotsForexTradeRoute,
  BotsForexIndexRoute: BotsForexIndexRoute,
}

const BotsForexRouteWithChildren = BotsForexRoute._addFileChildren(
  BotsForexRouteChildren,
)

interface BotsIndicesRouteChildren {
  BotsIndicesAnalysisRoute: typeof BotsIndicesAnalysisRoute
  BotsIndicesHistoryRoute: typeof BotsIndicesHistoryRoute
  BotsIndicesMarketsRoute: typeof BotsIndicesMarketsRoute
  BotsIndicesSettingsRoute: typeof BotsIndicesSettingsRoute
  BotsIndicesTradeRoute: typeof BotsIndicesTradeRoute
  BotsIndicesIndexRoute: typeof BotsIndicesIndexRoute
}

const BotsIndicesRouteChildren: BotsIndicesRouteChildren = {
  BotsIndicesAnalysisRoute: BotsIndicesAnalysisRoute,
  BotsIndicesHistoryRoute: BotsIndicesHistoryRoute,
  BotsIndicesMarketsRoute: BotsIndicesMarketsRoute,
  BotsIndicesSettingsRoute: BotsIndicesSettingsRoute,
  BotsIndicesTradeRoute: BotsIndicesTradeRoute,
  BotsIndicesIndexRoute: BotsIndicesIndexRoute,
}

const BotsIndicesRouteWithChildren = BotsIndicesRoute._addFileChildren(
  BotsIndicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  BotsForexRoute: BotsForexRouteWithChildren,
  BotsIndicesRoute: BotsIndicesRouteWithChildren,
  OauthCallbackRoute: OauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
